syntax = "proto3";

package meme.token.v1;

option go_package = "github.com/meme-launchpad/app-rebuild/gen/token/v1;tokenv1";

import "google/protobuf/timestamp.proto";

service TokenService {
  rpc ListTokens(ListTokensRequest) returns (ListTokensResponse);
  rpc GetToken(GetTokenRequest) returns (GetTokenResponse);
}

message ListTokensRequest {
  optional int32 page = 1;
  optional int32 page_size = 2;
}

message ListTokensResponse {
  repeated Token items = 1;
  int32 page = 2;
  int32 page_size = 3;
}

message GetTokenRequest {
  string contract_address = 1;
}

message GetTokenResponse {
  Token token = 1;
}

message Token {
  int64 id = 1;
  string name = 2;
  string symbol = 3;
  string logo = 4;
  optional string description = 5;
  string contract_address = 6;
  string creator_address = 7;
  int32 launch_mode = 8;
  string bnb_current = 9;
  string bnb_target = 10;
  string total_supply = 11;
  int32 status = 12;
  google.protobuf.Timestamp created_at = 13;
}
